name: demo
description: "A demo to show how microsites work"
github: "https://github.com/47deg/microsites"
docs: false

author: "47 Degrees"
author_url: "http://47deg.com"
license_name: The MIT License
license_url: https://opensource.org/licenses/MIT
markdown: redcarpet
collections:
  tut:
    output: true
