name: Microsites
description: "It enriches your library with a fancy documentation site"
github_owner: 47deg
url: http://47deg.github.io/microsites
baseurl: /microsites
style: default
docs: true

markdown: redcarpet
collections:
  tut:
    output: true

cdn:
  url: https://rawgit.com/47deg/microsites/cdn/

favicon:
  url: http://www.47deg.com/assets/img/custom/favicon.png

twitter: "@47deg"

organization:
  url: http://www.47deg.com/
  name: 47 Degrees